/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Glen' at '3/19/16 4:49 PM' with Gradle 2.12
 *
 * @author Glen, @date 3/19/16 4:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
