/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gwmccort' at '10/29/15 1:50 PM' with Gradle 2.8
 *
 * @author gwmccort, @date 10/29/15 1:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
